# Generated by Django 4.2.9 on 2026-03-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("first_disposal", "First Disposal"),
                            ("amr_hero", "AMR Hero"),
                            ("safe_champion", "Safe Medicine Champion"),
                            ("community_leader", "Community Leader"),
                            ("eco_warrior", "Eco Warrior"),
                            ("health_guardian", "Health Guardian"),
                        ],
                        max_length=30,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="core.citizen",
                    ),
                ),
            ],
            options={
                "ordering": ["earned_at"],
                "unique_together": {("citizen", "badge_type")},
            },
        ),
    ]
