# Generated by Django 4.2.9 on 2026-03-31 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of phone (optional)",
                        max_length=64,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-total_points"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("generic_name", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                (
                    "antibiotic_class",
                    models.CharField(
                        choices=[
                            ("penicillin", "Penicillins"),
                            ("cephalosporin", "Cephalosporins"),
                            ("macrolide", "Macrolides"),
                            ("fluoroquinolone", "Fluoroquinolones"),
                            ("tetracycline", "Tetracyclines"),
                            ("aminoglycoside", "Aminoglycosides"),
                            ("sulfonamide", "Sulfonamides"),
                            ("carbapenem", "Carbapenems"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "amr_risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("disposal_instructions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("area", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(default="", max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("accepts_expired", models.BooleanField(default=True)),
                (
                    "operating_hours",
                    models.CharField(default="9AM - 9PM", max_length=200),
                ),
                ("total_verified", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Pharmacies",
            },
        ),
        migrations.CreateModel(
            name="DisposalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("medicine_barcode", models.CharField(blank=True, max_length=100)),
                ("antibiotic_class", models.CharField(blank=True, max_length=50)),
                ("amr_risk_level", models.CharField(default="medium", max_length=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit", models.CharField(default="tablets", max_length=20)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — QR generated, awaiting drop-off"),
                            ("submitted", "Submitted — at pharmacy, awaiting scan"),
                            ("verified", "Verified — pharmacy confirmed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_home_disposal", models.BooleanField(default=False)),
                ("disposal_method", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("points_awarded", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposals",
                        to="core.citizen",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disposals",
                        to="core.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
